return {
	Bump = { Magnitude = 2.5, Roughness = 4, FadeInTime = 0.1, FadeOutTime = 0.75 },

	BigBump = { Magnitude = 2.5, Roughness = 4, FadeInTime = 0.1, FadeOutTime = 0.75 },

	SmallBump = { Magnitude = 2.5, Roughness = 4, FadeInTime = 0.1, FadeOutTime = 0.75 },

	Explosion = { Magnitude = 10, Roughness = 50, FadeInTime = 0, FadeOutTime = 0.5 },

	Impact = { Magnitude = 10, Roughness = 20, FadeInTime = 0, FadeOutTime = 2 },

	BumpRemaked = { Magnitude = 2, Roughness = 5, FadeInTime = 0, FadeOutTime = 1 },

	BigExplosion = { Magnitude = 20, Roughness = 40, FadeInTime = 0, FadeOutTime = 2 },

	ReallyBigExplosion = { Magnitude = 30, Roughness = 50, FadeInTime = 0, FadeOutTime = 1.5 },

	SmallExplosion = { Magnitude = 2.5, Roughness = 5, FadeInTime = 0, FadeOutTime = 1.5 },

	ExplosionNormal = { Magnitude = 5, Roughness = 10, FadeInTime = 0, FadeOutTime = 1.5 },

	Earthquake = { Magnitude = 0.6, Roughness = 3.5, FadeInTime = 2, FadeOutTime = 10 },

	BadTrip = { Magnitude = 10, Roughness = 0.15, FadeInTime = 5, FadeOutTime = 10 },

	HandheldCamera = { Magnitude = 1, Roughness = 0.25, FadeInTime = 5, FadeOutTime = 10 },

	Vibration = { Magnitude = 2, Roughness = 20, FadeInTime = 2, FadeOutTime = 2 },

	RoughDriving = { Magnitude = 1, Roughness = 2, FadeInTime = 1, FadeOutTime = 1 },

	SmallImpact = { Magnitude = 2, Roughness = 20, FadeInTime = 0, FadeOutTime = 0.5 },
}
