[package]
name = "azvar/runes-battlegrounds"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
topbarplus = "1foreverhd/topbarplus@3.4.0"

[server-dependencies]
dataservicetyped = "leifstout/dataservicetyped@1.0.3"