return {
	Info = {
		Order = 1,
		Icon = "rbxassetid://0",

		Special = {
			Action = "None",
		},
		UltimateSpecial = {
			Action = "None",
		},

		UltimateTime = 45,
		UltimateName = "Forgotten Warrior",
	},

	Moves = {
		["Punch"] = {
			Desc = "Punch them really hard.",
			Icon = "rbxassetid://139007402456420",
			CustomGradient = "Shattered",
		},
		["Combo"] = {
			Desc = "Stomp the ground to launch nearby enemies, then slam down on them with a devastating punch.",
			Icon = "rbxassetid://139007402456420",
			CustomGradient = "Shattered",
		},
		["Suplex"] = {
			Desc = "Grab a nearby enemy and suplex them into the ground.",
			Icon = "rbxassetid://139007402456420",
			CustomGradient = "Shattered",
		},
		["Parry"] = {
			Desc = "Brace yourself, if someone hits you while parrying, slam them into the ground.",
			Icon = "rbxassetid://139007402456420",
			CustomGradient = "Shattered",
		},
	},

	AwakeningMoves = {
		["Oblivion"] = {
			Desc = "Leap into the air, aim, and crash your fists down on the marked location, dealing massive area damage.",
			Icon = "rbxassetid://139007402456420",
			CustomGradient = "Shattered",
		},
	},

	UltimateName = "Forgotten Warrior",

	SpecialDisplay = nil,
}
