-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgMHBXBhaXJzBnNjcmlwdAtHZXRDaGlsZHJlbgxNb2R1bGVTY3JpcHQDSXNBBE5hbWUHcmVxdWlyZQABCQAAAQAAG6MAAAD/AAAAAAAAAKQBAQAAAABApAIDAAAAIEC8AgJoBAAAAJ8CAgCfAQAEFwEMAG8IBQC8BgX+BgAAAJ8GAwIOBgcATQYFugcAAACkBwkAAACAQFIIBQCfBwICagcABm4B8/8CAAAAggACAAoDAQQAAABAAwIEAAAgQAMDAwQDBQMGAwcEAACAQAABAAEYAAEAAQAAAAAAAAAAAQAAAAABAAAAAAAA/gAFAQAAAAAAeNH9TtIQdZRKFZfarkbOKByifEdk3hE9qja/0pxcHM6S1uokrgAKnA==

local v0 = {};
for _, v2 in pairs(script:GetChildren()) do
    if v2:IsA("ModuleScript") then
        v0[v2.Name] = require(v2);
    end;
end;
return v0;