return {
	Version = "v0.0.2",

	UpdateLog = {
		"Fixed Dashes",
		"Made indicators replicate to everyone",
		"Made lunar awaken moon be throwable upwards",
	},

	Roadmap = {
		"Death Sound game pass",
		"VIP game pass + aura + crown in ur rune",
		"2 Shattered moves",
		"Downslam and uppercut vfx",
		"Ranked and rank titles",
		"New solar awaken move",
		"New lunar awaken move",
		"Settings",
		"Change grasp to be a use twice move, once to cast the hand twice to pull",
		"Variant if tethers is used and no one is airborne",
		"Kill badges",
	},
}
