return {
	Version = "v0.0.4",

	UpdateLog = {
		"Added new topbar icons",
		"New cosmetics UI (free cosmetics soon!)",
		"Prowl and Punch can now hit ragdolled enemies if landed propely (uppercut + skill)",
		"Changed front dash, should be way better now",
		"Shattered Punch got a VFX rework!",
		"Grasp is now an use twice move, once to summon the hand and mark the, twice to pull",
		"New VIP gamepass, gives you a rune cosmetic and an aura",
		"Fixed an issue when swapping from Shattered to Eclipse",
		"Nightstalk now is aimable while in the ground",
		"You now get a free evasive on respawn",
		"Kill Streak is added",
		"New map lighting",
		"Changed solar rune model",
		"Made it so if you hold m1 it m1s as soon as possible (fixes holding m1 after grasp and prowl)",
	},

	Roadmap = {
		"2 Shattered moves",
		"Ranked and rank titles",
		"New solar awaken move",
		"New lunar awaken move",
		"Settings",
		"Variant if tethers is used and no one is airborne",
	},
}

-- shatter counter: hulk loki
