return {
	Version = "v0.0.3",

	UpdateLog = {
		"Added kill badges",
		"Made Dash not hit ragdolled enemies",
		"Added kill sound gamepass",
		"Added vfx for downslam and uppercut",
	},

	Roadmap = {
		"VIP game pass + aura + crown in ur rune",
		"2 Shattered moves",
		"Ranked and rank titles",
		"New solar awaken move",
		"New lunar awaken move",
		"Settings",
		"Change grasp to be a use twice move, once to cast the hand twice to pull",
		"Variant if tethers is used and no one is airborne",
	},
}

-- shatter counter: hulk loki
